package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ISMA
 */
public class penyetujuPelamar extends javax.swing.JFrame {

    /**
     * Creates new form penyetujuPelamar
     */
    public penyetujuPelamar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idlowongan = new javax.swing.JLabel();
        idlowonganfield = new javax.swing.JTextField();
        btnSetuju = new javax.swing.JButton();
        namajabatanfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idlowongan.setText("Id Lowongan   :");

        idlowonganfield.setText("003");
        idlowonganfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idlowonganfieldActionPerformed(evt);
            }
        });

        btnSetuju.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        btnSetuju.setText("Setuju");

        namajabatanfield.setText("namajabatan");
        namajabatanfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namajabatanfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btnSetuju))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(idlowongan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idlowonganfield, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(namajabatanfield, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(namajabatanfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idlowonganfield, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idlowongan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addComponent(btnSetuju)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namajabatanfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namajabatanfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namajabatanfieldActionPerformed

    private void idlowonganfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idlowonganfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idlowonganfieldActionPerformed

    /**
     * @param args the command line arguments
     */

    public JButton getBtnSetuju() {
        return btnSetuju;
    }

    public String getIdlowonganfield() {
        return idlowonganfield.getText();
    }

    public String getNamajabatanfield() {
        return namajabatanfield.getText();
    }

    public void setIdlowonganfield(String idlowonganfield) {
        this.idlowonganfield.setText(idlowonganfield);
    }

    public void setNamajabatanfield(String namajabatanfield) {
        this.namajabatanfield.setText(namajabatanfield);
    }
    public void addListener(ActionListener e){
        btnSetuju.addActionListener(e);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSetuju;
    private javax.swing.JLabel idlowongan;
    private javax.swing.JTextField idlowonganfield;
    private javax.swing.JTextField namajabatanfield;
    // End of variables declaration//GEN-END:variables
}
